### ISSUE TITLE
Infra stuff for page rendering

### ISSUE THREAD

**Issue by cycle20** [cycle20/scancer#3]
###### DONE by d186184 on branch [main](https://github.com/cycle20/scancer/tree/main) _( [gh-page](https://github.com/cycle20/scancer/tree/gh-pages) test commit: f0d7c9c )_

----

#### Why we need this?
- To achieve automated refresh of datasets and their visual presentation
- To build a reproducible environment (containerized way)
----
#### Subtasks
- [x] prototyping: docker image on a developer machine
- [x] prototyping: prepare a GitHub-hosted runner to execute our scripts
- [x] conditional job exec according to cache content
- [x] download pre-fetched data from GoogleDrive
- [x] create shareable UniProt pkg and store it on GoogleDrive
- [x] artifacts up/download and uniprot cache access from workflow
- [x] get last successful artifact from previous runs
- [x] uniprot cache append to dataPatch cache structure
- [x] webhooks: from spreadsheet **OR** from GitHub
      at least we need one direction
- [x] read spreadsheet on drive from R
- [x] call page render from workflow
- [x] deploy rendering result as gh-pages

###### postponed
* r-env !!! to speed up job inits
* ~~downloadable/re-usable docker image for project needs~~

#### others

- [x] ~~docker image remote exec in a _cloud environment_ **OR**~~ simple _GitHub Action_ ? :thinking: 
      NOTE: GitHub Action **DONE** :v: 
- [x] triggered running of a runner by push/pull request
- [x] triggered running of a runner on ~~**input list changes**~~ editors manual action on input list
      Button embedded into the spreadsheet.

**Comment by cycle20** [comment]
- [ ] https://dev.to/dtinth/caching-docker-builds-in-github-actions-which-approach-is-the-fastest-a-research-18ei

**Comment by cycle20** [comment]
DONE
